In [1]:
%load_ext autoreload
%autoreload 2
%cd ..

/home/ubuntu/latent-diffusion-lm


In [2]:
from src.task.sgpt import SGPTTask
from coop.models.sgpt import SentenceGPT
import torch
from datasets import load_dataset
from hydra import initialize, compose
from hydra.core.global_hydra import GlobalHydra

/home/ubuntu/.local/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
if GlobalHydra.instance().is_initialized():
    GlobalHydra.instance().clear()
initialize("../config/")
config = compose("sgpt")
config

/tmp/ipykernel_1076252/1463963186.py:3: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  initialize("../config/")


{'optimizer': {'cls': 'adam', 'learning_rate': 0.001}, 'logger': {'name': 'wandb'}, 'dataset': {'train': ['heegyu/aihub_daily_conv_2022'], 'test': ['heegyu/aihub_daily_conv_2022']}, 'model': {'model': 'sgpt-base.json', 'autoencoder': 'checkpoint/optimus-v2-56M/optimus-v2-mini-vae.ckpt', 'latent_dim': 512, 'free_bit': 0.5, 'max_seq_len': 16, 'is_vae': False}, 'trainer': {'train_batch_size': 8, 'train_epochs': 10, 'shuffle': False, 'eval_batch_size': 8, 'eval_strategy': 'epoch', 'project': 'sgpt', 'run_name': 'base-opt56M', 'num_sanity_val_steps': 1, 'limit_train_batches': 1, 'limit_val_batches': 1}}

In [45]:
sgpt = SGPTTask(config).cuda()

In [31]:
batch = next(iter(sgpt.train_dataloader()))
batch[0]

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


Using custom data configuration heegyu--aihub_daily_conv_2022-ee6ad77711466ab5
Reusing dataset parquet (/home/ubuntu/.cache/huggingface/datasets/heegyu___parquet/heegyu--aihub_daily_conv_2022-ee6ad77711466ab5/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec)
Using custom data configuration heegyu--aihub_daily_conv_2022-ee6ad77711466ab5
Reusing dataset parquet (/home/ubuntu/.cache/huggingface/datasets/heegyu___parquet/heegyu--aihub_daily_conv_2022-ee6ad77711466ab5/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec)


{'id': 140329,
 'depth': 18,
 'speakers': [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
 'utterances': ['**는 게임 좋아하니?',
  '게임 어떤거 좋아해?',
  '게임 잘 못해서,',
  '우린 완전 게임 좋아해',
  '나는 별로 안 좋아해',
  '어떤 게임 주로 하세요?',
  '그럼... 보드 게임은 어대',
  '게임은 너무 시간낭비야',
  '보드게임은 단합하기 좋죵',
  '우리는 음 맞고도 치고 루미 큐브도 하고',
  '게임 할 시간에 난 책을 읽어',
  '요즘 보드게임 카페 잘 되어 있잖아용',
  '너 책 2년 동안 한권도 안 읽었...',
  '책을 읽는 게 좋아',
  '와우 엄청난 지식인',
  '보드 게임 카페가 있어?',
  '책은 정말 너무신기해',
  '넵 요즘 애들 다 보드게임 카페가용 키키'],
 'eous': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [6]:
loss, output = sgpt.step(batch, 0)

In [7]:
loss

tensor(42.9597, device='cuda:0', grad_fn=<DivBackward0>)

In [40]:
item, sents = sgpt._item_for_train(batch[0]["utterances"][:4])
item

{'inputs': Normal(loc: torch.Size([16, 512]), scale: torch.Size([16, 512])),
 'attention_mask': tensor([1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0'),
 'labels': Normal(loc: torch.Size([16, 512]), scale: torch.Size([16, 512]))}

In [53]:
sgpt.step(batch, 0)

(tensor(324.8142, device='cuda:0', grad_fn=<DivBackward0>),
 SentenceGPTOutput(latent=Normal(loc: torch.Size([8, 16, 512]), scale: torch.Size([8, 16, 512])), zkl=tensor(0., device='cuda:0', grad_fn=<DivBackward0>), zkl_real=tensor(0.2608, device='cuda:0', grad_fn=<DivBackward0>)))

In [16]:
# item["inputs"].loc[3] - item["labels"].loc[2]
item["labels"].loc[1]

tensor([-0.6543,  0.4514, -0.4496, -0.2011,  0.1571, -0.0082, -0.0254,  0.3639,
        -0.5781, -0.0607, -0.2672, -0.3125, -0.4056,  0.3304,  0.1396, -0.0600,
         0.7875,  0.2400,  0.0881, -0.0476, -0.5376,  0.5642, -0.0779,  0.3077,
         0.2767, -0.2557,  0.1148, -0.0906,  0.1007, -0.4733, -0.4064,  0.0548,
        -0.3299, -0.5833, -0.4356, -0.6809,  0.7531, -0.3078,  0.0793,  0.7509,
        -0.0198,  0.5229, -0.0683, -0.5755, -0.1218,  0.0679,  0.3972,  0.1757,
         0.2055,  0.7688,  0.2889,  0.2690,  0.5317,  0.8551, -0.2805,  0.2565,
        -0.0550, -0.2084,  0.2662,  0.6917,  0.1499, -0.1584,  0.2070, -0.0642,
         0.0641,  0.3821,  0.5269,  0.1041,  0.1698, -0.0727,  0.2339, -0.1018,
         0.1608,  0.0769, -0.2124,  0.0286,  0.5587,  0.1368, -0.4899, -0.4216,
        -0.1526, -0.2055,  0.1048,  0.3757, -0.3938, -0.1050, -0.2472, -0.1659,
        -0.5944, -0.0657, -0.1364,  0.2998, -0.3014,  0.4246,  0.1183, -0.1263,
         0.1283,  0.1112, -0.2316,  0.76

In [27]:
hidden = sgpt.model.model(
    inputs_embeds = item["inputs"].rsample().unsqueeze(0),
    attention_mask = item["attention_mask"].unsqueeze(0)
).last_hidden_state
x = sgpt.model.reparameterize(hidden)
hidden.shape, x

TypeError: tuple indices must be integers or slices, not str

In [68]:
from torch.distributions import Normal, kl_divergence

labels = Normal(
    item["labels"].loc.unsqueeze(0),
    item["labels"].scale.unsqueeze(0)
)
labels

Normal(loc: torch.Size([1, 16, 512]), scale: torch.Size([1, 16, 512]))

In [77]:
print(labels.loc[0, 2, :])

tensor([-1.0166e-01,  2.6448e-01,  4.6458e-01,  1.0069e-01, -1.2405e-01,
        -5.1134e-02, -1.4447e-01,  1.1437e-01,  5.2955e-01, -1.9023e-02,
         2.8022e-01,  3.5747e-01,  1.6090e-01, -4.1626e-02,  7.3284e-02,
        -1.9380e-01,  1.1013e+00,  9.2238e-02,  8.4387e-01,  1.7632e-01,
        -2.2174e-01, -4.0417e-01,  7.6656e-02,  3.6906e-01,  9.0171e-02,
        -1.3099e-01,  1.6960e-01, -5.4958e-01,  3.4345e-01,  1.7964e-01,
         5.0326e-01,  4.7890e-01, -2.0597e-02,  1.7637e-01, -2.6835e-01,
         1.7770e-01, -7.9549e-01, -1.0125e-01, -1.0733e-02,  9.0773e-02,
         1.6803e-01,  6.4719e-01,  3.9788e-01,  7.4002e-01,  6.0794e-01,
         3.9314e-01,  4.8075e-01, -4.4489e-01, -4.4656e-01,  5.4711e-01,
        -3.4176e-01, -7.0742e-02, -3.0671e-01, -2.6214e-01,  1.4209e-01,
        -2.7931e-01,  3.9125e-01, -4.0892e-01, -7.2583e-01, -3.9219e-01,
         3.6348e-02,  1.3070e-01,  2.7684e-01,  3.2558e-01, -2.7234e-01,
        -1.1607e-01,  2.2687e-04, -2.6895e-01, -3.6

In [72]:

def kldiv_loss(free_bit, p: Normal, q: Normal, attention_mask: torch.Tensor = None, use_free_bit: bool = True):
    zkl_real = kl_divergence(p, q).mean(-1)

    if attention_mask is not None:
        attn_sum = attention_mask.sum()
        zkl_real = zkl_real.masked_fill(attention_mask == 0, 0.0)
    else:
        attn_sum = p.loc.shape[0] * p.loc.shape[1]

    if use_free_bit:
        kl_mask = torch.gt(zkl_real, free_bit)
        zkl = zkl_real[kl_mask].sum() / attn_sum
        zkl_real = zkl_real.sum() / attn_sum

        return zkl, zkl_real
    else:
        zkl_real = zkl_real.sum() / attn_sum
        return zkl_real
        
# kldiv_loss(
#     0.5,
#     x,
#     labels,
#     attention_mask = item["attention_mask"],
#     use_free_bit=False
# )
kl_divergence(x, labels).mean(-1)

tensor([[5.2743e+01, 4.5951e+01, 5.6947e+01, 7.6523e+11, 7.5514e+11, 7.4267e+11,
         7.5617e+11, 7.6696e+11, 7.6777e+11, 7.3560e+11, 7.6166e+11, 7.3166e+11,
         7.4869e+11, 7.6578e+11, 7.6710e+11, 7.5890e+11]], device='cuda:0',
       grad_fn=<MeanBackward1>)

In [17]:
sgpt.autoencoder.decoder(
    **tgt,
    past_key_values=(latent,),
    latent_as_gpt_memory=True,
    latent_as_gpt_emb=True,
    return_dict=True,
    **decoder_kwargs,
)

OptimusTask(
  (model): Optimus(
    (encoder): RobertaModel(
      (embeddings): RobertaEmbeddings(
        (word_embeddings): Embedding(32000, 512, padding_idx=1)
        (position_embeddings): Embedding(66, 512, padding_idx=1)
        (token_type_embeddings): Embedding(1, 512)
        (LayerNorm): LayerNorm((512,), eps=1e-12, elementwise_affine=True)
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (encoder): RobertaEncoder(
        (layer): ModuleList(
          (0): RobertaLayer(
            (attention): RobertaAttention(
              (self): RobertaSelfAttention(
                (query): Linear(in_features=512, out_features=512, bias=True)
                (key): Linear(in_features=512, out_features=512, bias=True)
                (value): Linear(in_features=512, out_features=512, bias=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
              (output): RobertaSelfOutput(
                (dense): Linear(in_features=512, out_features